### ISSUE TITLE
Left some API design comments on commits

### ISSUE THREAD

**Issue by rxwei** [eaplatanios/swift-rl#1]
I find the code super interesting and left some random comments on API naming. Take them as a grain of salt! I might start contributing at some point.

**Comment by eaplatanios** [comment]
@rxwei it's been a while since I was active in this repository, but I now need this for my research and have been pushing lots of updates over the past week. This now also contains a general reinforcement learning library that encompasses the functionality of OpenAI Gym, as well as TF-Agents and other RL libraries. It's currently under very active development and early draft stage, but it already supports lots of cool stuff (e.g., you can see a generic implementation of Advantage Actor Critic [A2C] [here](https://github.com/eaplatanios/retro-swift/blob/master/Sources/ReinforcementLearning/Agents/AdvantageActorCritic.swift) and an example of how to use it [here](https://github.com/eaplatanios/retro-swift/blob/master/Sources/ReinforcementLearningExperiments/CartPole.swift)). I have also started implementing some environments in pure Swift and also support visualizing this using a tentative API I made for OpenGL.

I just wanted to ping you in case you're interested to take a look and to also potentially start a discussion around features that are currently missing from S4TF but are super useful for an applied project like this one. In either case, I'll keep updating this and hope that by the end of the month we can have a pretty complete library for reinforcement learning in Swift. :)

**Comment by eaplatanios** [comment]
Also, cc @dan-zheng and @saeta.
